[package]
name = "rustm"
version = "0.1.0"
authors = ["jrybicki-jsc <j.rybicki@fz-juelich.de>"]
edition = "2018"

[lib]
crate-type =["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
