[package]
name = "guis"
version = "0.1.0"
authors = ["jrybicki-jsc <j.rybicki@fz-juelich.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.6.3" }
